"""test1

Revision ID: 23199f6323dc
Revises: 982a7bcc28b4
Create Date: 2021-10-17 16:17:49.449827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23199f6323dc'
down_revision = '982a7bcc28b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hot_water', sa.Float(), nullable=True),
    sa.Column('cold_water', sa.Float(), nullable=True),
    sa.Column('day_el', sa.Float(), nullable=True),
    sa.Column('night_el', sa.Float(), nullable=True),
    sa.Column('last_month_hot_water', sa.Float(), nullable=True),
    sa.Column('last_month_cold_water', sa.Float(), nullable=True),
    sa.Column('last_month_day_el', sa.Float(), nullable=True),
    sa.Column('last_month_night_el', sa.Float(), nullable=True),
    sa.Column('flat_number', sa.Integer(), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('date_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flats')
    # ### end Alembic commands ###
