"""second

Revision ID: 982a7bcc28b4
Revises: 10566b7b0fba
Create Date: 2021-10-17 16:03:05.692499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982a7bcc28b4'
down_revision = '10566b7b0fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
